#pragma once
#define IMCODEC_BUILD_CODEC_PNG 1
#define IMCODEC_BUILD_CODEC_JPG 1
#define IMCODEC_BUILD_CODEC_PSD 1
#define IMCODEC_BUILD_CODEC_FREE_IMAGE 1
#define IMCODEC_BUILD_CODEC_DDS 1
#define IMCODEC_BUILD_CODEC_TIFF 1

