name: Build Windows

on:
  workflow_call:

env:
  VULKAN_SDK: ''

jobs:
  build-linux-mingw64:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    container:
      image: ghcr.io/openimageviewer/openimageviewer/oiv-builder-arch:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Trust checkout directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Cache Vulkan SDK
      uses: actions/cache@v4
      with:
        path: ${{ env.BUILD_DIR }}/_deps/vulkan-sdk
        key: vulkan-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ hashFiles('OIVLib/Renderers/OIVVKRenderer/VulkanSDK.cmake') }}

    - name: Configure CMake
      run: >
        cmake
        -G Ninja
        -S "$GITHUB_WORKSPACE"
        -B "$BUILD_DIR"
        -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/mingw-w64-x86_64.cmake"
        -DIMCODEC_BUILD_CODEC_WEBP=OFF
        -DFREETYPE_WRAPPER_BUILD_FRIBIDI=OFF
        -DMINGW_POST_BUILD_DONT_COPY_BINARIES=ON

    - name: Build
      run: cmake --build "$BUILD_DIR" -- -j$(nproc)

  build-windows:
    runs-on: windows-2025-vs2026
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Cache Vulkan SDK
      uses: actions/cache@v4
      with:
        path: ${{ env.BUILD_DIR }}/_deps/vulkan-sdk
        key: vulkan-${{ runner.os }}-${{ runner.arch }}-${{ github.job }}-${{ hashFiles('OIVLib/Renderers/OIVVKRenderer/VulkanSDK.cmake') }}

    - name: Configure CMake
      run: >
        cmake -B "$env:BUILD_DIR"
        -S "$env:GITHUB_WORKSPACE"

    - name: Build
      run: cmake --build "$env:BUILD_DIR" --config Release
